export default [
  {
    id: "1",
    name: "Wrap",
    icon: "burrito",
    description: "Wrap con 2 fetas de queso y 4 fetas de fiambre.",
    protein: 38.61,
    fat: 42.5,
    carbs: 50.6,
  },
  {
    id: "2",
    name: "Wrap 🌿",
    icon: "burrito",
    description: "Wrap veggie con 2 fetas de queso, palta, tomate y lechuga.",
    protein: 44.7,
    fat: 49,
    carbs: 49.1,
  },
  {
    id: "3",
    name: "Sandwich",
    icon: "sandwich",
    description: "Sandwich con 1 feta de queso y 3 fetas de fiambre.",
    protein: 36.61,
    fat: 40.5,
    carbs: 33.3,
  },
  {
    id: "4",
    name: "Sandwich 🌿",
    icon: "sandwich",
    description:
      "Sandwich veggie con 2 fetas de queso, lechuga y tomate o palta.",
    protein: 42.7,
    fat: 47,
    carbs: 37.8,
  },
  {
    id: "5",
    name: "Taquito carne",
    icon: "burrito",
    description: "Taquito con carne de cerdo o pollo, ketchup, beans y choclo.",
    protein: 44.97,
    fat: 40.435,
    carbs: 49.1,
  },
  {
    id: "6",
    name: "Bread slice",
    icon: "bread",
    description: "One slice of white bread.",
    protein: 2.3,
    fat: 0.8,
    carbs: 9.9,
  },
  {
    id: "7",
    name: "Peanut butter",
    icon: "peanut-butter",
    description: "One spoonful (25g) of peanut butter.",
    protein: 6.75,
    fat: 13.25,
    carbs: 4.25,
  },
  {
    id: "8",
    name: "Peanuts",
    icon: "peanut",
    description: "10 peanuts, nuts or cashews (25g).",
    protein: 7.3,
    fat: 6.1,
    carbs: 13.8,
  },
  {
    id: "9",
    name: "Tarta acelga",
    description: "2 porciones de tarta de acelga.",
    icon: "tart",
    protein: 27.6,
    fat: 34.35,
    carbs: 38.25,
  },
  {
    id: "9.5",
    name: "Tarta J&Q",
    icon: "tart",
    description: "2 porciones de jamon y queso.",
    protein: 37.9,
    fat: 51.65,
    carbs: 32.25,
  },
  {
    id: "9.6",
    name: "Tarta atun",
    icon: "tart",
    description: "2 porciones de empanada gallega.",
    protein: 21.8,
    fat: 18.5,
    carbs: 57.5,
  },
  {
    id: "10",
    name: "Burger (patty)",
    icon: "burger",
    description: "Plain burger (patty) with some ketchup.",
    protein: 7.3,
    fat: 6.1,
    carbs: 13.8,
  },
  {
    id: "11.5",
    name: "Burger",
    icon: "burger",
    description: "Complete burger (buns, patty, lettuce, egg and ketchup).",
    protein: 37.6,
    fat: 44.4,
    carbs: 35.2,
  },
  {
    id: "11.6",
    name: "Empanada",
    icon: "dumpling",
    description: "Una empanada de carne o jamon y queso.",
    protein: 8.7,
    fat: 14.2,
    carbs: 24.1,
  },
  {
    id: "11",
    name: "Fish nuggets",
    icon: "fish",
    description: "4 fish sticks or chicken nuggets.",
    protein: 15.6,
    fat: 9.6,
    carbs: 21.2,
  },
  {
    id: "12",
    name: "Diced meat",
    icon: "meat",
    description: "130 grams of pork, chicken or beef.",
    protein: 36.64,
    fat: 22.83,
    carbs: 0,
  },
  {
    id: "12.1",
    name: "Steak",
    icon: "steak",
    description: "Beef steak or mileansea",
    protein: 53.8,
    fat: 14.4,
    carbs: 20,
  },
  {
    id: "13",
    name: "Egg",
    icon: "egg",
    description: "1 boiled egg.",
    protein: 6.1,
    fat: 5.6,
    carbs: 0.1,
  },
  {
    id: "14",
    name: "Baby carrots",
    icon: "carrot",
    description: "10 baby carrots (100 grams).",
    protein: 0.5,
    fat: 0.3,
    carbs: 13.6,
  },
  {
    id: "15",
    name: "Potatoes",
    icon: "potato",
    description: "1 serving of mashed or baked potatoes",
    protein: 9.255,
    fat: 14.46,
    carbs: 53.04,
  },
  {
    id: "16",
    name: "Torrejas",
    icon: "broccoli",
    description: "4 torrejas de brocoli o arroz.",
    protein: 2.261,
    fat: 14.763,
    carbs: 20.083,
  },
  {
    id: "16.5",
    name: "Pasta",
    description: "One medium serving of spaghetti with tomato sauce.",
    icon: "noodles",
    protein: 13.5,
    fat: 5.9,
    carbs: 54.5,
  },
  {
    id: "17",
    name: "Pop-corn",
    description: "Half a bowl of pop-corn.",
    icon: "pop-corn",
    protein: 2.9,
    fat: 13.5,
    carbs: 22,
  },
  {
    id: "18",
    name: "Fruit",
    icon: "kiwi",
    description: "1 kiwi, 1 orange, 10 grapes, 1 tangerine or half an apple",
    protein: 0.5,
    fat: 0.3,
    carbs: 13.6,
  },
  {
    id: "19",
    name: "Chocolate",
    descriptions: "One block (50g) of dark chocolate",
    icon: "chocolate",
    protein: 0.53,
    fat: 2.9,
    carbs: 5.4,
  },
  {
    id: "19.1",
    name: "Cookie",
    description: "Tree normal cookies or two chocolate-chip cookies",
    icon: "cookie",
    protein: 1.1,
    fat: 4.1,
    carbs: 15.3,
  },
  {
    id: "20",
    description: "3 slices of home-made pizza.",
    name: "Pizza",
    icon: "pizza",
    protein: 20.2,
    fat: 21.6,
    carbs: 51.5,
  },
  {
    id: "21",
    description:
      "Fries with ketchup (oven or air-fried) or nachos with guacamole.",
    name: "Fries",
    icon: "fries",
    protein: 4.8,
    fat: 19.5,
    carbs: 51.4,
  },
];
